### ISSUE TITLE
Bug: 本地化部署最后一步 run application.java报错

### ISSUE THREAD

**Issue by LuShanYanYu7** [CodePhiliaX/Chat2DB#1571]
### Chat2DB Version

github latest

### Describe the bug

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-11-19 16:07:10.993 ERROR 45313 --- [           main] o.s.boot.SpringApplication              .823 :  | Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userTeamAdminConverterImpl' defined in class path resource [ai/chat2db/server/admin/api/controller/user/converter/UserTeamAdminConverterImpl.class]: Failed to instantiate [ai.chat2db.server.admin.api.controller.user.converter.UserTeamAdminConverterImpl]: Constructor threw exception
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1314)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1199)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
        at ai.chat2db.server.web.start.Application.main(Application.java:70)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ai.chat2db.server.admin.api.controller.user.converter.UserTeamAdminConverterImpl]: Constructor threw exception
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1308)
        ... 17 common frames omitted
Caused by: java.lang.Error: Unresolved compilation problems: 
        UserTeamAdminConverter cannot be resolved to a type
        The method request2param(UserPageCommonQueryRequest) of type UserTeamAdminConverterImpl must override or implement a supertype method
        The method dto2vo(TeamUser) of type UserTeamAdminConverterImpl must override or implement a supertype method

        at ai.chat2db.server.admin.api.controller.user.converter.UserTeamAdminConverterImpl.<init>(UserTeamAdminConverterImpl.java:18)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:198)
        ... 19 common frames omitted

**Comment by tmlx1990** [comment]
您好，您其他相关的组件编译了吗？

**Comment by LuShanYanYu7** [comment]
编译了 就是按照文档里的操作来的 maven版本和Java版本也对的上

--------------原始邮件--------------
发件人："Xin&nbsp;Yan ***@***.***&gt;;
发送时间：2024年11月20日(星期三) 中午11:08
收件人："CodePhiliaX/Chat2DB" ***@***.***&gt;;
抄送："方佳俊 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [CodePhiliaX/Chat2DB] Bug: 本地化部署最后一步 run application.java报错 (Issue #1571)
-----------------------------------

 

 
您好，您其他相关的组件编译了吗？

**Comment by tmlx1990** [comment]
> 编译了 就是按照文档里的操作来的 maven版本和Java版本也对的上
> 
> --------------原始邮件--------------
> 发件人："Xin&nbsp;Yan ***@***.***&gt;;
> 发送时间：2024年11月20日(星期三) 中午11:08
> 收件人："CodePhiliaX/Chat2DB" ***@***.***&gt;;
> 抄送："方佳俊 ***@***.***&gt;;"Author ***@***.***&gt;;
> 主题：Re: [CodePhiliaX/Chat2DB] Bug: 本地化部署最后一步 run application.java报错 (Issue #1571)
> -----------------------------------
> 
>  
> 
>  
> 您好，您其他相关的组件编译了吗？
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是按这个执行的吗？![Screenshot_20241120_121334_com.huawei.browser.jpg](https://github.com/user-attachments/assets/24e37f20-5209-440a-9a5e-0e78bc38c705)

**Comment by LuShanYanYu7** [comment]
是的

**Comment by LuShanYanYu7** [comment]
操作视频 我提交到Chat2DB技术交流群55里了

**Comment by tmlx1990** [comment]
> 操作视频 我提交到Chat2DB技术交流群55里了

我今天重新用另一台电脑，可以正常启动的。要不你在idea中，运行下这个然后再启动试试：
<img width="859" alt="image" src="https://github.com/user-attachments/assets/b29eb79d-f71a-42de-bc7f-b63478d118b9">

**Comment by LuShanYanYu7** [comment]
运行这个没问题 但还是有之前的问题
