### ISSUE TITLE
Bug: 连接人大金仓数据库，1、右键修改表，查看ddl操作查看表结构，失败，报错，2、在列表中修改数据，保存无效

### ISSUE THREAD

**Issue by songyi123** [CodePhiliaX/Chat2DB#1609]
### Chat2DB Version

Chat2DB Pro2.14.1

### Describe the bug

ERROR: column tc.is_deferrable does not exist Position: 227 At Line: 1, Line Position: 227 KSQLException:com.kingbase8.util.KSQLException
com.kingbase8.util.KSQLException: ERROR: column tc.is_deferrable does not exist
  Position: 227 At Line: 1, Line Position: 227
	at com.kingbase8.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2679)
	at com.kingbase8.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
	at com.kingbase8.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:318)
	at com.kingbase8.jdbc.KbStatement.executeInternal(KbStatement.java:472)
	at com.kingbase8.jdbc.KbStatement.execute(KbStatement.java:392)
	at com.kingbase8.jdbc.KbStatement.executeWithFlags(KbStatement.java:333)
	at com.kingbase8.jdbc.KbStatement.executeCachedSql(KbStatement.java:319)
	at com.kingbase8.jdbc.KbStatement.executeWithFlags(KbStatement.java:296)
	at com.kingbase8.jdbc.KbStatement.execute(KbStatement.java:291)
	at ai.chat2db.spi.sql.SQLExecutor.execute(SQLExecutor.java:57)
	at ai.chat2db.plugin.kingbase.KingBaseMetaData.indexes(KingBaseMetaData.java:68)
	at ai.chat2db.server.domain.core.impl.TableServiceImpl.query(TableServiceImpl.java:96)
	at ai.chat2db.server.web.api.controller.rdb.TableController.query(TableController.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**Comment by Ryoui** [comment]
我也遇到了，今天试用的时候，一样的错误。
Chat2DB Pro 2.14.1。
数据库版本：V009R001
驱动：kingbase8-8.6.1.jar(也试过默认的8.6.0)
操作系统：win11 23H2

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.

**Comment by openai0229** [comment]
Thanks for reporting this. Chat2DB Community 5.3.x is a major new baseline rather than a patch on the historical release line. The database client core, local storage, packaging, and AI integrations have changed substantially, so this report against the previous architecture cannot be treated as a current 5.3.1 defect. We are closing this historical issue as outdated, not claiming that the exact symptom was individually fixed. For Community, please back up existing data and test with a fresh 5.3.1 installation because historical Community releases do not support an in-place upgrade. For Pro or Local, please test with the current corresponding edition. If the problem is still reproducible, open a new issue using the current template with the edition, OS, database version, steps, and logs.
